"""empty message

Revision ID: c191d8bd8bf1
Revises: 3fbc370761bd
Create Date: 2023-04-17 01:37:20.223076

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c191d8bd8bf1'
down_revision = '3fbc370761bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
